
version: '3'

services:
  database:
    container_name: database
    image: postgres:12-alpine
    restart: always
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=food

  api:
    depends_on:
      - database
    container_name: api
    restart: always
    build: ./api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_HOST=144.22.153.135
      - DB_NAME=food
      - DB_PORT=5400
      - API_KEY=dcea45dee6ed4f50834f13a52413b043
