version: '3'

networks:
  api:
    name: api_vps
    driver: bridge

services: 
  postgres:
    container_name: postgres_db
    image: postgres:12-alpine
    restart: always
    ports:
      - "5400:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=food
    networks:
      api:
        aliases: 
          - postgres_db

  back:
    depends_on:
      - postgres
    container_name: backend
    restart: always
    build: ./
    ports:
      - "4000:${PORT}"
    environment:
      - PORT=${PORT}               # recordar colocar el .env a la misma altura que el compose!!!
      - DB_USER=${DB_USER}         # a la hora del up, revisar que ambos .env esten iguales
      - DB_PASSWORD=${DB_PASSWORD} # el que esta dentro de /api y en la raiz!!!
      - DB_HOST=postgres_db        # porque a la hora de hacer el build toma el .env que esta a la 
      - DB_NAME=${DB_NAME}         # altura del compose. Otra seria crear otro compose dentro de api
      - DB_PORT=${DB_PORT}
      - API_KEY=${API_KEY}
    networks:
      api:
        aliases: 
          - api_api

